### ISSUE TITLE
NBF time checking issue

### ISSUE THREAD

**Issue by nelsonich** [peterpetrus/passport-token#4]
I found an issue with NBF time checking at line 96: https://github.com/peterpetrus/passport-token/blob/master/src/PassportToken.php#L96

The JWT token generator uses `new DateTimeImmutable()` instead of `time()`, so issue appears when after login I called API immediately.

- My current timestamp is: `1659786174.3179`
- NotBefore timestamp is: `1659786174.1458`

It was checking `1659786174.1458 > 1659786174` which is `true`, but it's need to check `1659786174.1458 > 1659786174.3179`.

That's why I'm getting an invalid token error.

---

My suggesstion: *use `$now = microtime(true);` instead of `$now = time();`*

---

Best regards,
Nelson

**Comment by peterpetrus** [comment]
The issue has been fixed. Thanks for your suggestion.
Best regards,
Peter
